version: "3"

services:
  dns-recursive-container:
    image: ghcr.io/aasaam/dns-recursive-container:latest
    container_name: dns-recursive-container
    hostname: dns-recursive-container
    # custom forwarders and access.conf
    # volumes:
    #   - ./forwarders.conf:/forwarders.conf:ro
    #   - ./access.conf:/access.conf:ro
    # env file include
    env_file:
      - ./.env
    environment:
      # enable DNSSEC (Domain Name System Security Extensions) validation and DOT (DNS over TLS)
      - STRICT_MODE=1

    # expose
    network_mode: host
    # or expose just require ports
    # ports:
    #   - "53:53/udp"
    #   - "53:53"
